---
title: "About the projection model"
author: "Siple MC and Punt AE"
date: 'Last updated: June 12, 2020'
output:
  html_document:
    highlight: tango
    theme: flatly
  pdf_document: default
  word_document: default
---

<!-- NOTE: in order to include this html in the shiny app, delete everything in the knitted html before <body> and after </body> -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# devtools::install_github("haozhu233/kableExtra")
 library(kableExtra)
```

```{r, child='../../vignettes/model-contents.Rmd')}
```

<!-- ### Citations -->
<!-- Arso Civil, M., Cheney, B., Quick, N.J., Islas-Villanueva, V., Graves, J.A., Janik, V.M., et al. (2019). Variations in age- and sex-specific survival rates help explain population trend in a discrete marine mammal population. Ecology and Evolution, 9, 533–544. -->

<!-- Breiwick, J.M., Eberhardt, L.L. & Braham, H.W. (1984). Population Dynamics of Western Arctic Bowhead Whales ( Balaena mysticetus ). Canadian Journal of Fisheries and Aquatic Sciences, 41, 484–496. -->

<!-- Butterworth, D.S. & Punt, A.E. (1992). The Scientific Committee “...Agreed That The MSY Rate Would Most Likely Lie Between 1 and 4%” - But Which MSY Rate? Reports of the International Whaling Commission, 42, 583–591. -->

<!-- Butterworth, D.S., Punt, A.E., Oosthuizen, W.H., Wickens, P.A. (1995) The effects of future consumption by the Cape fur seal on catches and catch rates of the Cape hakes. 3. Modelling the dynamics of the Cape fur seal Arctocephalus pusillus pusillus. South African Journal of Marine Science, 16, 161–183. -->

<!-- DeLong, R.L., Melin, S.R., Laake, J.L., Morris, P., Orr, A.J. & Harris, J.D. (2017). Age- and sex-specific survival of California sea lions (Zalophus californianus) at San Miguel Island, California. Marine Mammal Science, 33, 1097–1125. -->

<!-- Dillingham, P.W., Moore, J.E., Fletcher, D., Cortés, E., Curtis, K.A., James, K.C., et al. (2016). Improved estimation of intrinsic growth rmax for long-lived species: integrating matrix models and allometry. Ecological Applications, 26, 322–333. -->

<!-- Moore 2019. Unpublished estimate following the methods of Dillingham et al. 2016. -->

<!-- Ólafsdóttir, D., Víkingsson, G. A., Halldórsson, S. D., & Sigurjónsson, J. (2003). Growth and reproduction in harbour porpoises (Phocoena phocoena) in Icelandic waters. NAMMCO Scientific Publications, 5, 195–210. -->

<!-- Punt, A. E. (1999). Annex R: A full description of the standard Baleen II model and some variants thereof. Division of Marine Research, CSIRO Marine Laboratories, Hobart, Australia. -->

<!-- Punt, A.E., Moreno, P., Brandon, J.R. & Mathews, M.A. (2018). Conserving and recovering vulnerable marine species: a comprehensive evaluation of the US approach for marine mammals. ICES Journal of Marine Science, 75, 1813–1831. -->
